--require('lspconfig').setup({
--  vim.api.nvim_create_autocmd('LspAttach', {
--    group = vim.api.nvim_create_augroup('kickstart-lsp-attach', { clear = true }),
--    callback = function(event)
--      local map = function(keys, func, desc, mode)
--        mode = mode or 'n'
--        vim.keymap.set(mode, keys, func, { buffer = event.buf, desc = 'LSP: ' .. desc })
--      end
--
--      map('grn', vim.lsp.buf.rename, 'Rename')
--
--      -- Execute a code action, usually your cursor needs to be on top of an error
--      -- or a suggestion from your LSP for this to activate.
--      map('gra', vim.lsp.buf.code_action, 'Goto Code Action', { 'n', 'x' })
--
--      -- Find references for the word under your cursor.
--      map('grr', require('telescope.builtin').lsp_references, 'Goto References')
--
--      -- Jump to the implementation of the word under your cursor.
--      --  Useful when your language has ways of declaring types without an actual implementation.
--      map('gri', require('telescope.builtin').lsp_implementations, 'Goto Implementation')
--
--      -- Jump to the definition of the word under your cursor.
--      --  This is where a variable was first declared, or where a function is defined, etc.
--      --  To jump back, press <C-t>.
--      map('grd', require('telescope.builtin').lsp_definitions, 'Goto Definition')
--
--      -- WARN: This is not Goto Definition, this is Goto Declaration.
--      --  For example, in C this would take you to the header.
--      map('grD', vim.lsp.buf.declaration, 'Goto Declaration')
--
--      -- Fuzzy find all the symbols in your current document.
--      --  Symbols are things like variables, functions, types, etc.
--      map('gO', require('telescope.builtin').lsp_document_symbols, 'Open Document Symbols')
--
--      -- Fuzzy find all the symbols in your current workspace.
--      --  Similar to document symbols, except searches over your entire project.
--      map('gW', require('telescope.builtin').lsp_dynamic_workspace_symbols, 'Open Workspace Symbols')
--
--      -- Jump to the type of the word under your cursor.
--      --  Useful when you're not sure what type a variable is and you want to see
--      --  the definition of its *type*, not where it was *defined*.
--      map('grt', require('telescope.builtin').lsp_type_definitions, 'Goto Type Definition')
--
--      -- This function resolves a difference between neovim nightly (version 0.11) and stable (version 0.10)
--      ---@param client vim.lsp.Client
--      ---@param method vim.lsp.protocol.Method
--      ---@param bufnr? integer some lsp support methods only in specific files
--      ---@return boolean
--      local function client_supports_method(client, method, bufnr)
--        if vim.fn.has 'nvim-0.11' == 1 then
--          return client:supports_method(method, bufnr)
--        else
--          return client.supports_method(method, { bufnr = bufnr })
--        end
--      end
--
--      -- The following two autocommands are used to highlight references of the
--      -- word under your cursor when your cursor rests there for a little while.
--      --    See `:help CursorHold` for information about when this is executed
--      --
--      -- When you move your cursor, the highlights will be cleared (the second autocommand).
--      local client = vim.lsp.get_client_by_id(event.data.client_id)
--      if client and client_supports_method(client, vim.lsp.protocol.Methods.textDocument_documentHighlight, event.buf) then
--        local highlight_augroup = vim.api.nvim_create_augroup('kickstart-lsp-highlight', { clear = false })
--        vim.api.nvim_create_autocmd({ 'CursorHold', 'CursorHoldI' }, {
--          buffer = event.buf,
--          group = highlight_augroup,
--          callback = vim.lsp.buf.document_highlight,
--        })
--
--        vim.api.nvim_create_autocmd({ 'CursorMoved', 'CursorMovedI' }, {
--          buffer = event.buf,
--          group = highlight_augroup,
--          callback = vim.lsp.buf.clear_references,
--        })
--
--        vim.api.nvim_create_autocmd('LspDetach', {
--          group = vim.api.nvim_create_augroup('kickstart-lsp-detach', { clear = true }),
--          callback = function(event2)
--            vim.lsp.buf.clear_references()
--            vim.api.nvim_clear_autocmds { group = 'kickstart-lsp-highlight', buffer = event2.buf }
--          end,
--        })
--      end
--
--      -- The following code creates a keymap to toggle inlay hints in your
--      -- code, if the language server you are using supports them
--      --
--      -- This may be unwanted, since they displace some of your code
--      if client and client_supports_method(client, vim.lsp.protocol.Methods.textDocument_inlayHint, event.buf) then
--        map('<leader>th', function()
--          vim.lsp.inlay_hint.enable(not vim.lsp.inlay_hint.is_enabled { bufnr = event.buf })
--        end, '[T]oggle Inlay [H]ints')
--      end
--    end,
--  })
--})

--vim.lsp.config('lua_ls', {
--  settings = {
--    Lua = {
--      runtime = {
--        -- Tell the language server which version of Lua you're using (most likely LuaJIT in the case of Neovim)
--        version = 'LuaJIT',
--      },
--      diagnostics = {
--        -- Get the language server to recognize the `vim` global
--        globals = {'vim'},
--      },
--      workspace = {
--        -- Make the server aware of Neovim runtime files
--        library = vim.api.nvim_get_runtime_file("", true),
--      },
--      -- Do not send telemetry data containing a randomized but unique identifier
--      telemetry = {
--        enable = false,
--      },
--    },
--  },
--})

--vim.lsp.config('solargraph', {
--    cmd = { 'docker-compose', 'exec', '-T', 'web', 'bundle', 'exec', 'solargraph', 'stdio' },
--    root_dir = lspconfig.util.root_pattern('.git', 'Gemfile'),
--    on_attach = function(client, bufnr)
--    end,
--})
--
--vim.lsp.config('ts_ls', {
--    before_init = function(params)
--      params.processId = vim.NIL
--    end,
--    cmd = { 'docker-compose', 'exec', '-i', 'web', 'typescript-language-server', '--stdio' },
--    root_dir = lspconfig.util.root_pattern('package.json', 'tsconfig.json', '.git'),
--    on_attach = function(client, bufnr)
--    end,
--})

-- Config emmet-ls
-- https://github.com/aca/emmet-ls
